name: Build
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        id: find_project
        with: 
          run: |
            $yypFile = Get-ChildItem -Path . -Include *.yyp -Recurse | Select-Object -First 1
            Write-Host "::set-output name=path::$($yypFile.FullName)"
      - name: Build
        uses: bscotch/igor-build@v1
        with:
          version: latest
          project: ${{ steps.find_project.outputs.path }}
          target: android
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: ./Build
