name: Build
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: bscotch/igor-build@v1
        with:
          yyp-path: "$(Build.SourcesDirectory)/PizzaTower_Deggcomplantedshaderless3whydiditcorruptatthelastupdate.yyp"
          platform: android
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: ./Build
